config/routes.rb
Shopping::Application.routes.draw do
  get "home/index"

  resources :shops

  resources :users

  resources :categories

  resources :items

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :big_img_url, :desc, :evaluate_score, :item_id, :link_url, :middle_img_url, :price, :review_count, :sale_amount, :small_img_url, :title

  belongs_to :category
  belongs_to :shop,:class_name => "Shop",:foreign_key => "shop_id",:foreign_type => "string"
  has_many :item_imgses,:class_name => "ItemImgs"

  def item_imgses
    ItemImgs.where("item_id=#{item_id}")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %><br />
    <%= f.text_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :link_url %><br />
    <%= f.text_field :link_url %>
  </div>
  <div class="field">
    <%= f.label :small_img_url %><br />
    <%= f.text_field :small_img_url %>
  </div>
  <div class="field">
    <%= f.label :middle_img_url %><br />
    <%= f.text_field :middle_img_url %>
  </div>
  <div class="field">
    <%= f.label :big_img_url %><br />
    <%= f.text_field :big_img_url %>
  </div>
  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :evaluate_score %><br />
    <%= f.text_field :evaluate_score %>
  </div>
  <div class="field">
    <%= f.label :sale_amount %><br />
    <%= f.number_field :sale_amount %>
  </div>
  <div class="field">
    <%= f.label :review_count %><br />
    <%= f.number_field :review_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Item</th>
    <th>Link url</th>
    <th>Small img url</th>
    <th>Middle img url</th>
    <th>Big img url</th>
    <th>Desc</th>
    <th>Title</th>
    <th>Price</th>
    <th>Evaluate score</th>
    <th>Sale amount</th>
    <th>Review count</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.item_id %></td>
    <td><%= item.link_url %></td>
    <td><%= item.small_img_url %></td>
    <td><%= item.middle_img_url %></td>
    <td><%= item.big_img_url %></td>
    <td><%= item.intro %></td>
    <td><%= item.title %></td>
    <td><%= item.price %></td>
    <td><%= item.evaluate_score %></td>
    <td><%= item.sale_amount %></td>
    <td><%= item.review_count %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Item:</b>
  <%= @item.item_id %>
</p>

<p>
  <b>Link url:</b>
  <%= @item.link_url %>
</p>

<p>
  <b>Small img url:</b>
  <%= @item.small_img_url %>
</p>

<p>
  <b>Middle img url:</b>
  <%= @item.middle_img_url %>
</p>

<p>
  <b>Big img url:</b>
  <%= @item.big_img_url %>
</p>

<p>
  <b>Desc:</b>
  <%= @item.intro %>
</p>

<p>
  <b>Title:</b>
  <%= @item.title %>
</p>

<p>
  <b>Price:</b>
  <%= @item.price %>
</p>

<p>
  <b>Evaluate score:</b>
  <%= @item.evaluate_score %>
</p>

<p>
  <b>Sale amount:</b>
  <%= @item.sale_amount %>
</p>

<p>
  <b>Review count:</b>
  <%= @item.review_count %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>